### PR TITLE
Changes of dimensions in plots and adding supply ceiling analysis

### PR DESCRIPTION
**Pull request by asimoesgomes**

### CODE REVIEW

**Comment by wwiecek** [comment]
The thing that you do in `ceiling.R`, it looks like you're running some code sequentially and then had to re-run e.g. `prioritisation` to get to the right answer (I'm not surprised). The code is not designed to run different scenarios in a loop, I think you would be much safer if you just 1) generate all results from scratch (like running run-all.R but with the "ceiling" or demographics settings changing across runs). 2) at the end of each run store the relevant data.frames. 
This way is the safest. It also avoids duplicating the code for generating these data.frames in another script. 

Would it be a lot of work to code it that way? We can discuss live.

**Comment by asimoesgomes** [comment]
Sure! I changed the script and am running it to check that the results are fine. It will take longer now.
I will try to update it on git today but in the worst case I will have more time to work on this tomorrow

**Comment by wwiecek** [comment]
Yes, it takes longer and a lot of calculations are repeated a bit needlessly, but nice to have clean code. Thanks for the super quick turnaround on this!

**Comment by asimoesgomes** [comment]
You are right, lower-efficacy, lower-efficacy-delay and kappa-impact can be removed from the loop for now.
But the parts that take the longest are prep-delta-for-fdf and prep-results.
I have time to clean up the code some more today, do you have other suggestions? 
Or I can help with the write-up and try to polish the text.

**Comment by wwiecek** [comment]
> You are right, lower-efficacy, lower-efficacy-delay and kappa-impact can be removed from the loop for now.
> But the parts that take the longest are prep-delta-for-fdf and prep-results.
> I have time to clean up the code some more today, do you have other suggestions?
> Or I can help with the write-up and try to polish the text.

Sorry, I missed this because I was busy with other things. I will merge this for now and let you know via email.

**Review by wwiecek — APPROVED** [review]

**Pull request merged**
